worker_processes 1;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
        server_name storepro.cloud www.storepro.cloud;

        location / {
            proxy_pass http://app_storeprocloud_frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://ms_infinitycore_security:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /appusers/ {
            rewrite ^/appusers/(.*) /$1 break;
            proxy_pass http://ms_users_storeprocloud:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Token $http_token;
        }

        location /appreport/ {
            rewrite ^/appreport/(.*) /$1 break;
            proxy_pass http://ms_reports_storeprocloud:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Token $http_token;
        }

        location /core/ {
            rewrite ^/core/(.*) /$1 break;
            proxy_pass http://ms_core_storeprocloud:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Token $http_token;
        }
    }

    server {
        listen 80;
        server_name infinityadmin.online www.infinityadmin.online;

        location / {
            proxy_pass http://admin_platform_app_management:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
