http {
    server {
        listen 80;
        server_name storepro.cloud www.storepro.cloud;

        location / {
            proxy_pass http://app_storeprocloud_frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name app2.com www.app2.com;

        location / {
            proxy_pass http://app_storeprocloud_frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
