version: '3.8'
services:
  commons_nginx_multidomain:
    image: docker.io/nginx:latest
    container_name: commons-nginx-multidomain
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/storepro.cloud:/etc/letsencrypt/storepro.cloud:ro
      - ./certs/infinityadmin.online:/etc/letsencrypt/infinityadmin.online:ro
    ports:
      - "443:443"
    networks:
      - infra_storeprocloud_network
      - infra_admin_platform_network
      - infra_security_network
networks:
  infra_storeprocloud_network:
    external: true
    name: infra-storeprocloud-network
  infra_admin_platform_network:
    external: true
    name: infra-admin-platform-network
  infra_security_network:
    external: true
    name: infra-security-network